[package]
name = "custom-profile"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ash = { version = "0.38", default-features = false, features = [
    "linked",
    "debug",
    "std",
] }
vulkan-profiles-ash = { path = "../../", features = ["linked", "debug"] }
